#!/usr/sbin/nft -f

flush ruleset

table inet filter {
        chain input {
                type filter hook input priority filter; policy drop;
                iifname "lo" counter accept
                tcp dport 22 counter accept
                tcp dport 443 counter accept
                tcp dport 80 counter accept
		ip protocol icmp counter accept
		ip protocol icmpv6 counter accept
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}
