#!/bin/sh
# Enable a php-fpm pool per user
out="$1/multi-user.target.wants"
mkdir -p "$out"
while IFS=: read -r unam pwd uid gid gecos home shell; do
	# only non-system users
	if [ ! "$uid" -ge 1000 ]; then
		continue
	fi

	# only users with login shells
	if [ "$shell" = "/usr/sbin/nologin" ] || [ "$shell" = "/bin/false" ]; then
		continue
	fi

	ln -s /etc/systemd/system/php8.4-fpm@.service \
		"$out/php8.4-fpm@$unam.service"
done </etc/passwd 
